name: Security Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-phase:
    name: Pre Phase - Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Pre Phase Security Scan
        uses: clockhash-kiran/scan-actions/pre-phase@main
        with:
          target_url: "https://github.com/clockhash-kiran/test-security-pipeline"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: "${{ secrets.API_TOKEN }}"

  build-image:
    name: Build & Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: pre-phase
    outputs:
      image_fullname: ${{ steps.image_name.outputs.full }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Image Name
        id: image_name
        run: echo "full=kirandockerch/test-security-image:latest" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t kirandockerch/test-security-image:latest .

      - name: Push Docker Image
        run: docker push kirandockerch/test-security-image:latest

  mid-phase:
    name: Mid Phase - Container Scan
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Mid Phase Security Scan
        uses: clockhash-kiran/scan-actions/mid-phase@main
        with:
          target_url: "kirandockerch/test-security-image:latest"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: "${{ secrets.API_TOKEN }}"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: mid-phase
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./app

  post-phase:
    name: Post Phase - Deployment Scan
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run Post Phase Security Scan
        uses: clockhash-kiran/scan-actions/post-phase@main
        with:
          target_url: "https://clockhash-kiran.github.io/test-security-pipeline"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: "${{ secrets.API_TOKEN }}"
