name: Security Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-phase:
    name: Pre Phase - Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Pre Phase Security Scan
        uses: clockhash-kiran/scan-actions/pre-phase@main
        with:
          target_url: "https://github.com/clockhash-kiran/test-security-pipeline"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: ${{ secrets.API_TOKEN }}

  build-image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: pre-phase
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u clockhash-kiran --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/clockhash-kiran/test-security-image:latest .

      - name: Push Image to GHCR
        run: docker push ghcr.io/clockhash-kiran/test-security-image:latest

      - name: Make GHCR Image Public
        run: |
          IMAGE="test-security-image"
          PACKAGE_URL="https://api.github.com/user/packages/container/$IMAGE/versions"
          VERSION_ID=$(curl -s -H "Authorization: token $GH_TOKEN" $PACKAGE_URL | jq '.[0].id')
          curl -X PATCH -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/packages/container/$IMAGE/versions/$VERSION_ID \
               -d '{"visibility":"public"}'
        env:
          GH_TOKEN: ${{ secrets.GHCR_PAT }}

  mid-phase:
    name: Mid Phase - Container Scan
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Run Mid Phase Security Scan
        uses: clockhash-kiran/scan-actions/mid-phase@main
        with:
          target_url: "ghcr.io/clockhash-kiran/test-security-image:latest"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: ${{ secrets.API_TOKEN }}

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: mid-phase
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app

  post-phase:
    name: Post Phase - Deployment Scan
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run Post Phase Security Scan
        uses: clockhash-kiran/scan-actions/post-phase@main
        with:
          target_url: "https://clockhash-kiran.github.io/test-security-pipeline"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "2dffeec3-f4e7-417a-bf5b-d178d2e690b3"
          api_token: ${{ secrets.API_TOKEN }}
